dev:
  host: staging.example.com
  host: localhost:8080
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
staging:
  host: staging.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
production:
  host: demo.mindhiking.info
  api_key: <your api key here>
